import type { LucideIcon } from 'lucide-react';
import { 
  Link2, 
  Globe, 
  BookOpen, 
  FileText, 
  Music, 
  Heart, 
  ShoppingBag, 
  Star, 
  Mail, 
  Phone, 
  MapPin, 
  Compass, 
  Coffee, 
  MessageCircle, 
  CheckCircle, 
  Zap, 
  Smile, 
  Code, 
  Camera, 
  Tv, 
  Headphones, 
  Feather, 
  Gift, 
  Bookmark, 
  Shield, 
  Flame, 
  Sparkles, 
  Laptop, 
  Video, 
  Send, 
  Share2, 
  ExternalLink,
  Podcast,
  Gamepad2,
  Store,
  Briefcase,
  Tag,
  Paperclip
} from 'lucide-react';

export interface IconItem {
  id: string;
  name: string;
  icon: LucideIcon;
  tags?: string[];
}

export const iconRegistry: Record<string, LucideIcon> = {
  link: Link2,
  globe: Globe,
  book: BookOpen,
  file: FileText,
  music: Music,
  heart: Heart,
  shopping: ShoppingBag,
  star: Star,
  mail: Mail,
  phone: Phone,
  mappin: MapPin,
  compass: Compass,
  coffee: Coffee,
  message: MessageCircle,
  check: CheckCircle,
  zap: Zap,
  smile: Smile,
  code: Code,
  camera: Camera,
  tv: Tv,
  headphones: Headphones,
  feather: Feather,
  gift: Gift,
  bookmark: Bookmark,
  shield: Shield,
  flame: Flame,
  sparkles: Sparkles,
  laptop: Laptop,
  video: Video,
  send: Send,
  share: Share2,
  external: ExternalLink,
  podcast: Podcast,
  gamepad: Gamepad2,
  store: Store,
  briefcase: Briefcase,
  tag: Tag,
  paperclip: Paperclip
};

export const availableIcons: IconItem[] = [
  { id: 'link', name: 'Link', icon: Link2, tags: ['chain', 'url', 'web'] },
  { id: 'globe', name: 'Website', icon: Globe, tags: ['internet', 'world', 'site'] },
  { id: 'book', name: 'Book', icon: BookOpen, tags: ['read', 'story', 'posttype'] },
  { id: 'file', name: 'Blog', icon: FileText, tags: ['article', 'text', 'post'] },
  { id: 'music', name: 'Music', icon: Music, tags: ['audio', 'song'] },
  { id: 'heart', name: 'Heart', icon: Heart, tags: ['like', 'love', 'sponsor'] },
  { id: 'shopping', name: 'Shop', icon: ShoppingBag, tags: ['store', 'buy'] },
  { id: 'star', name: 'Star', icon: Star, tags: ['favorite', 'review'] },
  { id: 'mail', name: 'Email', icon: Mail, tags: ['contact', 'letter'] },
  { id: 'phone', name: 'Phone', icon: Phone, tags: ['call', 'contact'] },
  { id: 'mappin', name: 'Location', icon: MapPin, tags: ['place', 'map'] },
  { id: 'compass', name: 'Compass', icon: Compass, tags: ['explore', 'guide'] },
  { id: 'coffee', name: 'Coffee', icon: Coffee, tags: ['buy me a coffee', 'donation'] },
  { id: 'message', name: 'Chat', icon: MessageCircle, tags: ['talk', 'message'] },
  { id: 'check', name: 'Check', icon: CheckCircle, tags: ['done', 'verify'] },
  { id: 'zap', name: 'Zap', icon: Zap, tags: ['fast', 'flash'] },
  { id: 'smile', name: 'Smile', icon: Smile, tags: ['happy', 'face'] },
  { id: 'code', name: 'Code', icon: Code, tags: ['dev', 'developer'] },
  { id: 'camera', name: 'Camera', icon: Camera, tags: ['photo', 'picture'] },
  { id: 'tv', name: 'TV', icon: Tv, tags: ['stream', 'video'] },
  { id: 'headphones', name: 'Podcast', icon: Headphones, tags: ['audio', 'listen'] },
  { id: 'feather', name: 'Writing', icon: Feather, tags: ['story', 'pen'] },
  { id: 'gift', name: 'Gift', icon: Gift, tags: ['present', 'free'] },
  { id: 'bookmark', name: 'Bookmark', icon: Bookmark, tags: ['save', 'mark'] },
  { id: 'shield', name: 'Shield', icon: Shield, tags: ['secure', 'safe'] },
  { id: 'flame', name: 'Popular', icon: Flame, tags: ['hot', 'fire'] },
  { id: 'sparkles', name: 'Sparkles', icon: Sparkles, tags: ['new', 'special'] },
  { id: 'laptop', name: 'Laptop', icon: Laptop, tags: ['work', 'computer'] },
  { id: 'video', name: 'Video', icon: Video, tags: ['movie', 'stream'] },
  { id: 'send', name: 'Send', icon: Send, tags: ['telegram', 'message'] },
  { id: 'share', name: 'Share', icon: Share2, tags: ['share', 'social'] },
  { id: 'external', name: 'External', icon: ExternalLink, tags: ['open', 'link'] },
  { id: 'podcast', name: 'Radio', icon: Podcast, tags: ['audio', 'broadcast'] },
  { id: 'gamepad', name: 'Gaming', icon: Gamepad2, tags: ['game', 'play'] },
  { id: 'store', name: 'Store', icon: Store, tags: ['market', 'shop'] },
  { id: 'briefcase', name: 'Portfolio', icon: Briefcase, tags: ['work', 'job'] },
  { id: 'tag', name: 'Tag', icon: Tag, tags: ['label', 'category'] },
  { id: 'paperclip', name: 'Attachment', icon: Paperclip, tags: ['file', 'clip'] },
];

export const getLinkIcon = (iconId?: string): LucideIcon => {
  if (!iconId || !iconRegistry[iconId]) {
    return Link2;
  }
  return iconRegistry[iconId];
};
